# syntax=docker/dockerfile:1

##############################################################
# Integration Test用RunnerBaseImage
##############################################################
# build & runコマンド
# docker build -t daichiwealsoft/integration_test_job_base_image:v1.0.0 .
# docker run -v C:\Users\besta\app\tech_blog\poc-frontend-app:/home/sample_app -p 3000:3000 -u root --name selenium_test21 -w /home/sample_app --rm -it daichiwealsoft/integration_test_job_base_image:v1.0.0 bash
FROM node:16.20.0-buster

RUN apt-get update && apt-get install wget -y

# 設定ファイルの読み込みにyqコマンド（jqのyaml版）を使用しているためインストール
# なお、yqは２種類あり、goが動作が安定しているためそれを使用
ARG VERSION=v4.2.0
ARG BINARY=yq_linux_amd64
RUN wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq &&\
    chmod +x /usr/bin/yq

# パッケージリストの更新とGoogle Chromeのインストール
# 最新バージョンのgoogle-chromeを取得して、バージョン取得してそれに応じたChromeDriverのバージョンを取得するような複雑なインストール処理を実行する必要があるため、shellに外だし
# windowsで開発している場合はshellの改行コードがLFになっていることを確認する。CRLFの場合は正常に動作しないので注意
COPY selenium_requirement.sh .
RUN chmod +x selenium_requirement.sh
RUN ./selenium_requirement.sh
