FROM node:16.20.0-buster

RUN apt-get update && apt-get install wget -y

# 設定ファイルの読み込みにyqコマンド（jqのyaml版）を使用しているためインストール
# なお、yqは２種類あり、goが動作が安定しているためそれを使用
ARG VERSION=v4.2.0
ARG BINARY=yq_linux_amd64
RUN wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq &&\
    chmod +x /usr/bin/yq
