name: js-blog-build-test

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER_NAME:
        required: true
      DOCKERHUB_USER_PASSWORD:
        required: true
    inputs:
      PIPELINE_REF:
        description: 'public-pipeline-makingのどのブランチをfetchするか'
        default: main
        required: false
        type: string
      INTEGRATION_TEST:
        description: 'Seleniumによる統合テスト実行フラグ'
        default: true
        required: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # TODO ジョブコンテナーを取りやめて、松本さん案のyqとsetup-nodeを使用する方法で高速化できるか確認する
      image: docker.io/daichiwealsoft/integration_test_job_base_image:v1.0.1
      credentials:
        username: ${{ secrets.DOCKERHUB_USER_NAME }}
        password: ${{ secrets.DOCKERHUB_USER_PASSWORD }}
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
      env:
        NODE_ENV: development
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: 'wealsoft/public-pipeline-making'
          path: './public-pipeline-making'
          ref: ${{ inputs.PIPELINE_REF }}

      - name: SetEnv
        env:
          PR_BRANCH_NAME: ${{ github.head_ref }}
        shell: bash
        run: |
          echo build_tag=${PR_BRANCH_NAME#*/} >> $GITHUB_ENV

      - name: SetConfigEnv
        shell: bash
        run: |
          CONFIG_COMMON_LIST=$(yq eval '.common' ./.github/config.yml | sed 's/\:\ /\=/')
          for config_common in $CONFIG_COMMON_LIST
          do
            echo "$config_common" >> $GITHUB_ENV
          done

      - name: Set Env for Pipeline Internal
        shell: bash
        run: |
          echo UPLOAD_STATIC_FILES_PATH=${{ github.workspace }}/upload-static-files >> $GITHUB_ENV

      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          path: "**/node_modules"
          key: node-modules-${{ hashFiles('**/package.json') }}
          restore-keys: node-modules-

      - name: Making the directory for github artifact upload
        shell: bash
        run: |
            mkdir ${{ env.UPLOAD_STATIC_FILES_PATH }}

      - name: App Src Build
        shell: bash
        run: |
            . ${{ github.workspace }}/${{ env.SHELL_FILE_PATH }} ${{ env.UPLOAD_STATIC_FILES_PATH }}

      - name: Upload to github artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-artifact
          path: ${{ env.UPLOAD_STATIC_FILES_PATH }}/*
          retention-days: 7

  # TODObuildxを使用して差分ビルド・さらにcacheアクションを使用して高速化する
  # buildジョブと並列で動作させる
  setup_integration_test:
    runs-on: ubuntu-latest
    if: ${{ inputs.INTEGRATION_TEST }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: 'wealsoft/public-pipeline-making'
          path: './public-pipeline-making'
          ref: ${{ inputs.PIPELINE_REF }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_USER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Image Cache
        uses: actions/cache@v3.0.11
        with:
          path: "/tmp/.buildx-cache"
          key: docker-job-container-images-${{ github.commit }}
          restore-keys: docker-job-container-images-

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/public-pipeline-making/.github
          file: ${{ github.workspace }}/public-pipeline-making/.github/Dockerfile_js_job_container
          push: true
          tags: docker.io/daichiwealsoft/integration_test_job_base_image:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # buildジョブと並列で動作させる
  setup_integration_test_for_service_container:
    needs: ['build']
    runs-on: ubuntu-latest
    if: ${{ inputs.INTEGRATION_TEST }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: 'wealsoft/public-pipeline-making'
          path: './public-pipeline-making'
          ref: ${{ inputs.PIPELINE_REF }}

      - name: Set Env for Internal
        shell: bash
        run: |
          echo DOWNLOAD_STATIC_FILES_PATH=${{ github.workspace }}/download-static-files >> $GITHUB_ENV

      - name: Making the directory for github artifact download
        shell: bash
        run: |
            mkdir ${{ env.DOWNLOAD_STATIC_FILES_PATH }}

      - uses: actions/download-artifact@v3
        with:
          name: built-artifact
          path: ${{ env.DOWNLOAD_STATIC_FILES_PATH }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_USER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Image Cache
        uses: actions/cache@v3.0.11
        with:
          path: "/tmp/.buildx-cache"
          key: docker-service-container-images-${{ github.commit }}
          restore-keys: docker-service-container-images-

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DOWNLOAD_STATIC_FILES_PATH }}
          file: ${{ github.workspace }}/public-pipeline-making/.github/Dockerfile_github_pages
          push: true
          tags: docker.io/daichiwealsoft/integration_test_service_image:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # dockerhub経由でコンテナーイメージを渡すようにする
  # 静的資材はartifact経由で受け渡す
  integration_test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: docker.io/daichiwealsoft/integration_test_service_image:latest
        ports:
          - 80:4000
    if: ${{ inputs.INTEGRATION_TEST }}
    needs: ['build','setup_integration_test','setup_integration_test_for_service_container']
    container:
      image: docker.io/daichiwealsoft/integration_test_job_base_image:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USER_NAME }}
        password: ${{ secrets.DOCKERHUB_USER_PASSWORD }}
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
      env:
        NODE_ENV: development
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: 'wealsoft/public-pipeline-making'
          path: './public-pipeline-making'
          ref: ${{ inputs.PIPELINE_REF }}

      - name: SetConfigEnv
        shell: bash
        run: |
          CONFIG_COMMON_LIST=$(yq eval '.common' ./.github/config.yml | sed 's/\:\ /\=/')
          for config_common in $CONFIG_COMMON_LIST
          do
            echo "$config_common" >> $GITHUB_ENV
          done

      - name: Set Env for Internal
        shell: bash
        run: |
          echo DOWNLOAD_STATIC_FILES_PATH=${{ github.workspace }}/download-static-files >> $GITHUB_ENV

      - name: Making the directory for github artifact download
        shell: bash
        run: |
            mkdir ${{ env.DOWNLOAD_STATIC_FILES_PATH }}

      - uses: actions/download-artifact@v3
        with:
          name: built-artifact
          path: ${{ env.DOWNLOAD_STATIC_FILES_PATH }}

      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          path: "**/node_modules"
          key: node-modules-${{ hashFiles('**/package.json') }}
          restore-keys: node-modules-

      - name: App Src Build
        shell: bash
        run: |
            . ${{ github.workspace }}/${{ env.INTEGRATION_TEST_SHELL_FILE_PATH }} ${{ env.DOWNLOAD_STATIC_FILES_PATH }}
